import {readFile} from 'node:fs/promises';
const esc = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export async function renderRedesign(sourceDir, office) {
  const data = JSON.parse(await readFile(`${sourceDir}/data/publications.json`, 'utf8'));
  if (data.series.length !== 8) throw new Error('The publication library must contain eight series');
  const ids = new Set(office.bots.map(b => b.id));
  for (const s of data.series) for (const id of s.desks) if (!ids.has(id)) throw new Error('Unknown publication desk: '+id);
  for (const id of ids) if (!data.series.some(s => s.desks.includes(id))) throw new Error('Bot lacks a publication responsibility: '+id);
  const desk = id => office.bots.find(b => b.id === id).name;
  const stewards = `<section class="content-section section-shell" id="stewards" lang="en" dir="ltr">
    <div class="section-heading"><div><p class="eyebrow">People carry the work forward</p><h2>Three stewards. A shared responsibility.</h2></div><p>Continuity begins with people: the writing system, its practice, and the infrastructure that helps it travel.</p></div>
    <div class="steward-grid">
    <article class="steward-card"><span class="steward-order">01 / First steward</span><h3>Valerie Sutton</h3><p class="steward-focus">The writing system</p><p>Creator of Sutton SignWriting. Her work anchors the symbols, the writer’s perspective, and the teaching of the writing system.</p><a href="https://www.signwriting.org/lessons/">Explore the original lessons ↗</a></article>
    <article class="steward-card"><span class="steward-order">02 / Second steward</span><h3>Adam Frost</h3><p class="steward-focus">Writing and teaching</p><p>SignWriting practice, ASL teaching, and the clarity of written signs. Writer and teacher experience belongs at the center of the work.</p><a href="mailto:education@signwriting.org?subject=SignWriting%20writing%20and%20teaching">Ask about writing and teaching ↗</a></article>
    <article class="steward-card"><span class="steward-order">03 / Third steward</span><h3>Steve Slevinski</h3><p class="steward-focus">Technology and continuity</p><p>Formal SignWriting, open tools, and the work of building a lasting business and institutional home for SignWriting.</p><a href="https://steveslevinski.me/">Read Steve’s work ↗</a></article></div>
    <p class="microcopy">The Office’s AI assistants support human judgment. These cards do not imply that an assistant speaks for a steward.</p></section>`;
  const work = `<section class="content-section section-shell" id="work" lang="en" dir="ltr"><div class="section-heading"><div><p class="eyebrow">A practical office</p><h2>What we have. How we help. What comes next.</h2></div><p>Available work and future plans have different labels so you can choose a useful next step.</p></div><div class="work-grid">
    <article class="work-card"><span class="state-label">Has · available now</span><h3>A place to begin</h3><ul><li>Public contact routes and learning resources</li><li>Eight published series to read and cite</li><li>Country and language orientation</li><li>Email registration of interest</li></ul><a href="#publications">Explore the publication library →</a></article>
    <article class="work-card"><span class="state-label">Can · through the Office</span><h3>Help move a question forward</h3><ul><li>Find sources and explain their limits</li><li>Prepare design and technical reviews</li><li>Route teaching, community, and support questions</li><li>Prepare evidence and options for human decisions</li></ul><a href="#contact">Find your contact route →</a></article>
    <article class="work-card"><span class="state-label">Will · proposed direction</span><h3>Build for continuity</h3><ul><li>Office sign-in and an invited community app</li><li>Clear permissions and resource limits</li><li>ISWA 2026 preparation</li><li>A 2027 publication and institutional program</li></ul><a href="https://www.sutton-signwriting.io/roadmap/">Follow the technology roadmap →</a></article>
    </div></section>`;
  const publications = `<section class="publication-section" id="publications" lang="en" dir="ltr"><div class="section-shell"><div class="section-heading"><div><p class="eyebrow">The reference library · ${esc(data.version)}</p><h2>Eight series.<br>A foundation to build on.</h2></div><p>Read the published record, follow its sources, or bring a question to the Office. The library serves people and gives our assistants a shared, citable reference.</p></div>
    <div class="publication-actions"><a class="button button-primary" href="https://doi.org/${esc(data.doi)}">Complete eight-series release ↗</a><a class="text-link" href="${esc(data.companions.find(c=>c.file==='how-to-read-the-platform.md').url)}">How to read the platform ↗</a><a class="text-link" href="data/publications.json">Machine-readable library ↓</a></div>
    <p class="publication-citation">Slevinski, S. (2026). Sutton SignWriting Platform: Complete Eight-Series Release (v1.0.0). Zenodo. DOI: ${esc(data.doi)}.</p>
    <p class="publication-note">Published v1 is an archival reference. Living source repositories may contain later edits. The proposed 2027 edition is a separate editorial project; it is not yet released. Desk assignments below are proposed for human review.</p>
    <div class="series-grid">${data.series.map((s,i)=>`<article class="series-card" id="series-${esc(s.slug)}"><span class="series-number">${String(i+1).padStart(2,'0')}</span><h3>${esc(s.title.replace('Sutton SignWriting ',''))}</h3><p>${esc(s.role)}</p><p class="series-desks">Reference desks: ${s.desks.map(id=>`<a href="#bot-${id}">${esc(desk(id))}</a>`).join(', ')}</p><div class="series-links"><a href="${esc(s.archiveUrl)}">Cite v1.0.0 ↗</a><a href="${esc(s.immutableSourceUrl)}">v1 source ↗</a><a href="${esc(s.living_url)}">Living edition ↗</a></div><details><summary>${s.entries.length} published entries</summary><ol>${s.entries.map(e=>`<li><a href="${esc(e.sourceUrl)}">${esc(e.title)}</a></li>`).join('')}</ol></details></article>`).join('')}</div>
    <details class="publication-companions"><summary>Reader paths, AI orientation, evaluation, and release manifests</summary><ul>${data.companions.map(c=>`<li><a href="${esc(c.url)}">${esc(c.file.replaceAll('-',' ').replace(/\.(md|json|csv)$/,''))}</a> · ${esc(c.edition)}</li>`).join('')}</ul></details>
    <aside class="publication-future"><div><p class="eyebrow">Looking toward 2027</p><h3>A lasting home for the next chapter.</h3><p>Steve’s next publication program connects the writing system and its evidence to stewardship, sustainable infrastructure, and an institutional home. The current eight series remain the reference while that next edition takes shape.</p></div><a class="button" href="mailto:research@signwriting.org?subject=2027%20publication%20program">Contribute a question →</a></aside>
    </div></section>`;
  return {stewards, work, publications};
}
